#!/bin/bash

# https://github.com/lyaguxafrog/python-backend-devcontainer


if [[ $1 = 'startproject' ]]; then
    printf "Which framework do you want to use?\n\n"
    printf "[1] Django\n"
    printf "[2] Flask\n"
    printf "[3] FastAPI\n"
    read -p "Enter the number: " framework_choice

    if [[ $framework_choice = '1' ]]; then
        printf "DRF(1) or Graphene(2)?\n"
    fi
fi
