#!/bin/bash


show_help() {
    echo "help"
}

delete_pbd() {

    read -p "Are you sure you want to delete PBD? [y/N] " answer
    if [ "$answer" = "y" ] || [ "$answer" = "Y" ]; then
        rm -rf /home/$USER/.pbd
        rm -rf /home/$USER/.local/bin/pbd
        echo "PBD deleted :("
    else
        echo "Aborted."
    fi
}

drf_template() {

    

}
